export enum WAITER_ACTION_TYPES {
    SET_CURRENT_USER= 'waiter/SET_CURRENT_USER',
    SIGN_IN_SUCCESS= 'waiter/SIGN_IN_SUCCESS',
    SIGN_IN_FAILED= 'waiter/SIGN_IN_FAILED',
    CHECK_USER_SESSION= 'waiter/CHECK_USER_SESSION',
    SIGN_OUT_START= 'waiter/SIGN_OUT_START',
    SIGN_OUT_SUCCESS= 'waiter/SIGN_OUT_SUCCESS',
    SIGN_OUT_FAILED= 'waiter/SIGN_OUT_FAILED',
    EMAIL_SIGN_IN_START= 'user/EMAIL_SIGN_IN_START',
    SIGN_UP_START= 'waiter/SIGN_UP_START',
    SIGN_UP_SUCCESS= 'waiter/SIGN_UP_SUCCESS',
    SIGN_UP_FAILED= 'waiter/SIGN_UP_FAILED',

}