export enum ORDER_INFO_ACTION_TYPES {
    SET_TABLE_TOTAL = "orderInfo/SET_TABLE_TOTAL",
    SET_USER_TOTAL_EQUAL = "orderInfo/SET_USER_TOTAL_EQUAL",
    SET_USER_TOTAL_MENU = "orderInfo/SET_USER_TOTAL_MENU",
    SET_TIPS = "orderInfo/SET_TIPS",
    SET_NEW_USERS_LIST = "orderInfo/SET_NEW_USERS_LIST",
    SET_IS_METHOD_MENU = "orderInfo/SET_IS_METHOD_MENU",
}